version: '3.8'

services:
  # Serviço para o MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exemplos
      MYSQL_USER: senac
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/main/resources/scripts:/docker-entrypoint-initdb.d
# Serviço para a sua aplicação Java
  java_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
